apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


images:
- name: argoproj/argocd
  newName: abhishekf5/argocd
  newTag: routeinfo
resources:
- ./application-controller
- ./dex
- ./repo-server
- ./server
- ./config
- ./redis
